baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Buğra Keskin Personal Page"

disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Buğra Keskin"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:mail@example.org"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/"
    
    [[params.links]]
        iconset = "fas"
        icon = "fas fa-address-card"
        title = "About-me"
        url = "#about"